import { AlertTriangle, ArrowLeft, Camera, Check, Clock, XCircle, Zap } from 'lucide-react'
import Badge from '../../common/Badge.jsx'
import Button from '../../common/Button.jsx'
import Card from '../../common/Card.jsx'

function QuestDetailsHeader({ quest, onBack, onAction, onFailure }) {
  const Icon = quest.icon
  const completed = quest.status === 'completed'
  const failed = quest.status === 'failed'
  const pendingVerification = quest.status === 'pending_verification'
  const skipped = quest.status === 'skipped'
  return <div><button type="button" onClick={onBack} className="mb-7 flex items-center gap-2 text-sm text-slate-500 transition hover:-translate-x-1 hover:text-cyan-200"><ArrowLeft size={16} />BACK TO DAILY QUESTS</button><Card variant="highlighted" className="relative overflow-hidden p-6 sm:p-8"><div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-cyan-300/10 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><span className="grid h-16 w-16 place-items-center rounded-2xl border border-cyan-300/30 bg-cyan-300/10 text-cyan-200 shadow-[0_0_30px_rgba(103,232,249,0.15)]"><Icon size={30} /></span><div><p className="label-caps text-cyan-300/70">{quest.category} / mission briefing</p><p className="mt-2 flex items-center gap-2 font-mono text-xs text-slate-500"><Clock size={13} />{quest.estimatedTime}</p></div></div><h1 className="mt-7 max-w-3xl font-display text-3xl font-semibold tracking-tight text-white sm:text-5xl">{quest.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-400">{quest.shortDescription}</p><div className="mt-6 flex flex-wrap gap-2"><Badge tone={completed ? 'success' : failed ? 'danger' : pendingVerification ? 'difficulty' : skipped ? 'category' : 'status'}>{completed ? 'Completed' : failed ? 'Failed' : pendingVerification ? 'Pending Verification' : skipped ? 'Skipped' : quest.status}</Badge><Badge tone="category">{quest.type} objective</Badge><Badge tone="difficulty">{quest.difficulty}</Badge>{quest.verification !== 'None' && <Badge tone="category"><Camera size={12} className="mr-1" />{quest.verification}</Badge>}</div></div><div className="flex flex-col items-start gap-4 lg:items-end"><div className="flex items-center gap-2 font-mono text-2xl text-amber-200"><Zap size={20} />+{quest.xp} XP</div>{completed ? <div className="flex items-center gap-2 font-mono text-sm text-emerald-200"><Check size={16} />+{quest.xp} XP EARNED</div> : pendingVerification ? <Button variant="secondary" disabled>VERIFICATION IN PROGRESS</Button> : failed ? <div className="flex items-center gap-2 font-mono text-sm text-amber-200"><XCircle size={16} />MISSION FAILED</div> : skipped ? <Badge tone="category">QUEST SKIPPED</Badge> : <div className="flex flex-wrap gap-2"><Button variant={quest.verification !== 'None' ? 'secondary' : 'primary'} onClick={onAction}>{quest.verification !== 'None' ? 'PROCEED TO VERIFICATION' : 'COMPLETE QUEST'}</Button><Button variant="ghost" onClick={onFailure}><AlertTriangle size={15} />MARK AS FAILED</Button></div>}</div></div></Card></div>
}
export default QuestDetailsHeader
