import { motion } from 'framer-motion'
import { ArrowUpRight, Cpu, Sparkles } from 'lucide-react'
import { NavLink } from 'react-router-dom'

function AuthLayout({ children, mode }) {
  return <div className="relative min-h-screen overflow-hidden bg-rankora-950 text-slate-100"><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(103,232,249,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(103,232,249,0.06)_1px,transparent_1px)] bg-size-[52px_52px] opacity-40" /><div className="pointer-events-none absolute -left-32 top-1/4 h-96 w-96 rounded-full bg-cyan-400/10 blur-3xl" /><div className="pointer-events-none absolute -right-32 bottom-0 h-112 w-md rounded-full bg-violet-400/10 blur-3xl" /><div className="relative mx-auto flex min-h-screen w-full max-w-360 flex-col px-5 py-6 lg:grid lg:grid-cols-[1fr_minmax(25rem,31rem)] lg:items-center lg:gap-20 lg:px-12 lg:py-10 xl:grid-cols-[1fr_31rem] xl:gap-32"><header className="flex items-center justify-between lg:absolute lg:left-12 lg:right-12 lg:top-8"><NavLink to="/login" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300 text-rankora-950 shadow-[0_0_24px_rgba(103,232,249,0.35)]"><Sparkles size={18} strokeWidth={2.5} /></span><span className="font-display text-lg font-bold tracking-[0.16em]">RANKORA</span></NavLink><span className="label-caps text-slate-600">{mode === 'login' ? 'System access' : 'Player identity'}</span></header><section className="flex flex-1 items-center py-14 lg:py-0"><motion.div initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.55, ease: 'easeOut' }} className="max-w-xl"><div className="mb-8 hidden h-px w-24 bg-linear-to-r from-cyan-300 to-transparent lg:block" /><p className="label-caps text-cyan-300/70">Authentication required</p><h1 className="mt-5 max-w-lg font-display text-4xl font-semibold leading-[1.05] tracking-tight text-white sm:text-6xl">FORGE YOUR <span className="text-cyan-200">PROGRESS.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-slate-400">Turn your daily actions into quests. Earn XP. Build discipline. Rank up.</p><div className="mt-10 hidden items-center gap-8 border-t border-white/10 pt-6 sm:flex"><div><p className="label-caps text-slate-600">Protocol</p><p className="mt-2 flex items-center gap-2 font-mono text-xs text-slate-300"><Cpu size={14} className="text-cyan-300" />Progression online</p></div><div><p className="label-caps text-slate-600">Cycle</p><p className="mt-2 flex items-center gap-2 font-mono text-xs text-slate-300"><ArrowUpRight size={14} className="text-violet-300" />01 / Initiation</p></div></div></motion.div></section><section className="flex items-center justify-center pb-4 lg:pb-0">{children}</section></div></div>
}

export default AuthLayout
